#!/usr/bin/env python3
"""Generate the classified production unsafe-site inventory."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
TOKEN = re.compile(r"\bunsafe\b")


def classification(path: str) -> tuple[str, str, str, str]:
    if "bsw-bsp-stm32" in path:
        if path.endswith("can_isr.rs"):
            return ("bsp-concurrency", "SPSC slots are exclusively owned by the published atomic cursors", "preserve the sole-producer/sole-consumer contract", "stm32-and-host-test")
        return ("bsp-hardware", "raw addresses refer to the selected MCU's documented MMIO or linker-owned memory", "select the matching MCU and uphold each function's register/pointer contract", "stm32")
    if "bsw-estd" in path:
        return ("container", "raw storage contains exactly the live elements described by length and link state", "respect capacity, lifetime, pinning, and exclusive-mutation contracts", "portable")
    if "bsw-util/src/spsc.rs" in path:
        return ("concurrency", "release/acquire cursors give one producer and one consumer exclusive slot ownership", "obtain handles only through split and do not duplicate them", "portable-atomic")
    if "bsw-util/src/buddy.rs" in path:
        return ("allocator", "computed tree indices and block addresses stay inside caller-provided storage", "provide aligned storage matching the configured geometry", "portable")
    if "bsw-can/src/socketcan.rs" in path:
        return ("can-posix-ffi", "libc socket calls receive valid descriptors, initialised sockaddr/frame structs, and correctly sized buffers", "keep every FFI argument's lifetime and size contract as documented at the call site", "linux-host")
    if "bsw-io/src/memory_queue.rs" in path:
        return ("io-concurrency", "published cursors separate writer-owned and reader-owned byte regions", "use exactly one writer and one reader obtained through split", "portable-atomic")
    return ("crate-owner", "the enclosing module's documented pointer and aliasing invariants hold", "follow the enclosing unsafe API contract", "portable")


def kind(code: str) -> str:
    if re.search(r"\bunsafe\s+impl\b", code):
        return "unsafe-impl"
    if re.search(r"\bunsafe\s+(?:extern\s+)?fn\b", code):
        return "unsafe-fn"
    if re.search(r"\bunsafe\s+extern\b", code):
        return "unsafe-extern"
    if re.search(r"\bunsafe\s*\{", code):
        return "unsafe-block"
    return "unsafe-token"


def sites() -> list[dict]:
    result: list[dict] = []
    for source in sorted((ROOT / "crates").rglob("*.rs")):
        relative = source.relative_to(ROOT).as_posix()
        lines = source.read_text(encoding="utf-8").splitlines()
        in_test_module = "/tests/" in relative
        for number, raw in enumerate(lines, 1):
            if raw.strip() == "#[cfg(test)]":
                in_test_module = True
                continue
            if in_test_module:
                continue
            code = raw.split("//", 1)[0]
            if not TOKEN.search(code):
                continue
            owner, invariant, obligations, target = classification(relative)
            for _ in TOKEN.finditer(code):
                result.append({
                    "id": f"U{len(result) + 1:04d}",
                    "path": relative,
                    "line": number,
                    "kind": kind(code),
                    "scope": "example" if "/examples/" in relative else "library",
                    "owner": owner,
                    "invariant": invariant,
                    "caller_obligations": obligations,
                    "target": target,
                    "review_status": "classified-for-package-review",
                })
    return result


def documents() -> tuple[str, str]:
    entries = sites()
    payload = {
        "schema_version": 1,
        "generated_from": "crates/**/*.rs",
        "production_site_count": len(entries),
        "sites": entries,
    }
    json_text = json.dumps(payload, indent=2) + "\n"
    owners = Counter(entry["owner"] for entry in entries)
    kinds = Counter(entry["kind"] for entry in entries)
    lines = [
        "# Production unsafe-code inventory",
        "",
        "> Generated by `tools/port/inventory_unsafe.py`; site-level classifications are in `unsafe-inventory.json`.",
        "",
        f"Classified production sites: **{len(entries)}**.",
        "",
        "Test-only code after a crate's `#[cfg(test)]` module is excluded. Deployable BSP examples are included.",
        "",
        "## Ownership summary",
        "",
        "| Owner | Sites |",
        "|---|---:|",
    ]
    lines.extend(f"| `{name}` | {count} |" for name, count in sorted(owners.items()))
    lines.extend(["", "## Site-kind summary", "", "| Kind | Sites |", "|---|---:|-"])
    lines[-1] = "|---|---:|"
    lines.extend(f"| `{name}` | {count} |" for name, count in sorted(kinds.items()))
    lines.extend([
        "",
        "Every JSON row records its path/line, owner, invariant, caller obligations, target, and review status. Line numbers are regenerated and must not be used as durable identifiers outside this inventory.",
        "",
    ])
    return json_text, "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    json_text, markdown = documents()
    outputs = {
        ROOT / "docs/port/unsafe-inventory.json": json_text,
        ROOT / "docs/port/unsafe-inventory.md": markdown,
    }
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items() if not path.exists() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != text]
        if stale:
            print(f"stale unsafe inventory: {', '.join(stale)}", file=sys.stderr)
            return 1
        print(f"unsafe inventory current: {len(json.loads(json_text)['sites'])} sites")
        return 0
    if args.write:
        for path, text in outputs.items():
            path.write_text(text, encoding="utf-8")
        print(f"wrote unsafe inventory: {len(json.loads(json_text)['sites'])} sites")
        return 0
    print(markdown, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
